# 任务一：对下面代码进行注释及解读。

In [1]:
import numpy as np     # 导入numpy库
X = np.random.randint(5, size=(6, 50))  # 返回在6到50之间6个随机整型数的函数，
y = np.array([1, 2, 3, 4, 5, 6])       # 创建列表

In [4]:
from sklearn.naive_bayes import MultinomialNB    # 导入MultinomialNB贝叶斯函数
clf = MultinomialNB(alpha = 0.01,fit_prior=True)   # 调取模型
clf.fit(X, y)            # 数据训练
print(clf.predict(X))    # 打印处预测值

[1 2 3 4 5 6]


alpha:制定平滑因子的值；

binarize:默认为1个浮点数0.0，表示以该数值为界，将特征取值大于它的编码为1，小于它的编码为0，从而实现对数据集的二值化；当使用binarize=None时，模型会假定你已经将数据二值化了；

fit_prior:制定是否计算P（Y=Ck）,默认为True,表示不计算P（Y=Ck），而直接用均匀分布代替；如果为False,则表示计算实际的P（Y=Ck）。

In [5]:
clf.score(X, y)    # 计算预测精度

1.0

# 任务二：利用处理好的数据DataClear，划分训练集和测试集，使用sklearn.naive_bayes.MultinomialNB 方法进行拟合，计算在测试集上的混淆矩阵、准确率。

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split

In [7]:
data = pd.read_csv('F:/大三（上）/机器学习/贝叶斯实践作业/实践作业/DataClear.csv')
data.head()

单位名称  换车  商户  吉林大路  还在  给出  安全标准  地  是因为  东北师范大学  ...  绿园  门将  研究所  世纪家园  \
0  市供热公司   0   0     0   0   0     0  0    0       0  ...   0   0    0     0   
1  市水务集团   0   0     0   0   0     0  0    0       0  ...   0   0    0     0   
2  市水务集团   0   0     0   0   0     0  0    0       0  ...   0   0    0     0   
3  市燃气集团   0   0     0   0   0     0  0    0       0  ...   0   0    0     0   
4  市公交集团   0   0     0   0   0     0  0    0       0  ...   0   0    0     0   

   水务  提醒  照  煦  煤  后门  
0   0   0  0  0  0   0  
1   0   0  0  0  0   0  
2   0   0  0  0  0   0  
3   0   0  0  0  0   0  
4   0   0  0  0  0   0  

[5 rows x 6236 columns]

In [8]:
# 将各个词汇的使用频数转换为0-1，0表示未出现某个词汇，而1表示出现了某个词汇
data.iloc[:, 1:] = np.where(data.iloc[:, 1:]>=1, 1, 0)

institution_name = data['单位名称'].unique()  
institution_dict = dict(zip(institution_name, range(len(institution_name))))
f = lambda x: institution_dict[x]
data['单位名称'] = data['单位名称'].apply(f)

In [9]:
data.head()

单位名称  换车  商户  吉林大路  还在  给出  安全标准  地  是因为  东北师范大学  ...  绿园  门将  研究所  世纪家园  \
0     0   0   0     0   0   0     0  0    0       0  ...   0   0    0     0   
1     1   0   0     0   0   0     0  0    0       0  ...   0   0    0     0   
2     1   0   0     0   0   0     0  0    0       0  ...   0   0    0     0   
3     2   0   0     0   0   0     0  0    0       0  ...   0   0    0     0   
4     3   0   0     0   0   0     0  0    0       0  ...   0   0    0     0   

   水务  提醒  照  煦  煤  后门  
0   0   0  0  0  0   0  
1   0   0  0  0  0   0  
2   0   0  0  0  0   0  
3   0   0  0  0  0   0  
4   0   0  0  0  0   0  

[5 rows x 6236 columns]

In [10]:
X = data.iloc[:, 1:].values
y = data['单位名称'].values

In [39]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 1) 
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((1600, 6235), (400, 6235), (1600,), (400,))

In [40]:
MNB = MultinomialNB()
MNB.fit(X_train,y_train)
y_pred = MNB.predict(X_test)
y_pred 

array([3, 3, 2, 3, 1, 5, 0, 5, 5, 3, 5, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 2,
       1, 3, 2, 1, 1, 3, 3, 3, 1, 3, 5, 5, 0, 0, 2, 5, 2, 2, 5, 3, 0, 2,
       1, 3, 3, 1, 1, 1, 4, 2, 5, 5, 5, 0, 5, 4, 5, 0, 2, 0, 1, 2, 5, 1,
       5, 5, 1, 2, 5, 1, 1, 1, 1, 1, 2, 0, 3, 2, 3, 2, 0, 5, 1, 0, 1, 1,
       0, 4, 1, 5, 3, 1, 3, 0, 0, 3, 5, 5, 5, 0, 1, 1, 0, 3, 5, 5, 0, 1,
       2, 2, 5, 0, 3, 1, 3, 1, 0, 1, 0, 0, 5, 1, 1, 3, 6, 3, 1, 2, 0, 2,
       5, 2, 5, 0, 0, 1, 3, 6, 5, 1, 4, 6, 2, 1, 0, 1, 0, 1, 1, 1, 2, 1,
       0, 0, 0, 0, 3, 5, 0, 3, 1, 0, 0, 3, 1, 0, 1, 0, 3, 2, 1, 1, 0, 1,
       0, 2, 1, 0, 2, 1, 0, 2, 5, 0, 1, 2, 0, 3, 1, 1, 1, 1, 1, 3, 2, 5,
       1, 5, 1, 0, 3, 1, 2, 1, 4, 0, 0, 3, 5, 2, 5, 1, 1, 2, 0, 6, 0, 3,
       1, 2, 2, 0, 1, 1, 1, 1, 1, 5, 1, 5, 0, 1, 5, 3, 1, 0, 3, 3, 5, 0,
       5, 4, 1, 6, 1, 1, 3, 1, 1, 3, 1, 1, 6, 1, 1, 0, 5, 1, 5, 5, 0, 1,
       1, 0, 0, 5, 1, 3, 5, 0, 2, 2, 5, 1, 0, 1, 0, 2, 0, 5, 4, 5, 1, 0,
       6, 6, 0, 0, 5, 0, 5, 5, 1, 5, 2, 0, 6, 2, 5,

In [41]:
confusion_matrix(y_test, y_pred)  #计算混淆矩阵

array([[ 76,   1,   0,   0,   0,   0,   0],
       [  0, 110,   0,   0,   0,   0,   0],
       [  0,   0,  46,   0,   0,   0,   0],
       [  0,   0,   0,  46,   0,   0,   0],
       [  5,   3,   1,   0,   9,   0,   0],
       [  0,   1,   0,   2,   0,  72,   0],
       [  0,   9,   2,   0,   0,   1,  16]], dtype=int64)

In [42]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred )   #计算准确率

0.9375